# Generated by Django 4.2.13 on 2024-06-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/sampleImg.jpg', upload_to='Images'),
        ),
    ]
